#!/bin/bash
# Submit VPT1 strategy (VPT-v18-strategy) generation.
# Runs keyboard_agent.py on task VPT-v18-strategy. Reset-driven: every step the
# agent emits action 5 which the env converts into another scene-generation
# attempt until STRATEGY_TARGET scenes are saved per array task.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
JOB_DIR="${REPO_ROOT}/VPTnav_code/cube_game/job_array/normal_vptnav"

BASE_PATH="${BASE_PATH:-/users/arock3/scratch/VPT1_DATA/thesis/v18_vpt_1_strategy}"
NUM_GPUS="${NUM_GPUS:-8}"
TASK="${TASK:-VPT-v18-strategy}"
NUM_NODES="${NUM_NODES:-10}"
NUM_ENVS="${NUM_ENVS:-32}"
TIME_LIMIT="${TIME_LIMIT:-03:00:00}"
MEMORY="${MEMORY:-40G}"
AGENT_SCRIPT="${AGENT_SCRIPT:-/mnt/VPT/VPTnav_code/cube_game/scripts/vptnav/keyboard_agent.py}"

# Strategy tuning defaults (override via env at submit time).
STRATEGY_TARGET="${STRATEGY_TARGET:-2000}"
STRATEGY_MAX_ATTEMPTS="${STRATEGY_MAX_ATTEMPTS:-250}"
STRATEGY_VERBOSE="${STRATEGY_VERBOSE:-1}"
STRATEGY_MIN_SELECTED_PAIR_DISTANCE="${STRATEGY_MIN_SELECTED_PAIR_DISTANCE:-0.25}"
STRATEGY_RAIL_EXTENT="${STRATEGY_RAIL_EXTENT:-6.0}"
SETTLE_STEPS="${SETTLE_STEPS:-30}"

LOG_DIR="${BASE_PATH}/logs"
DATA_DIR="${BASE_PATH}/data"
mkdir -p "${LOG_DIR}" "${DATA_DIR}"

echo "[VPTNAV] VPT1 strategy generation"
echo "  base=${BASE_PATH}"
echo "  task=${TASK} nodes=${NUM_NODES} gpus/node=${NUM_GPUS} envs/gpu=${NUM_ENVS}"
echo "  time=${TIME_LIMIT} mem=${MEMORY}"
echo "  STRATEGY_TARGET=${STRATEGY_TARGET} (per array task)"
echo "  STRATEGY_MIN_SELECTED_PAIR_DISTANCE=${STRATEGY_MIN_SELECTED_PAIR_DISTANCE}"
echo "  STRATEGY_RAIL_EXTENT=${STRATEGY_RAIL_EXTENT}  SETTLE_STEPS=${SETTLE_STEPS}"
echo "  agent=${AGENT_SCRIPT}"

# Forward every strategy knob that has been set in this submitter's env.
EXPORT_VARS="ALL"
EXPORT_VARS+=",BASE_PATH=${BASE_PATH}"
EXPORT_VARS+=",NUM_GPUS=${NUM_GPUS}"
EXPORT_VARS+=",TASK=${TASK}"
EXPORT_VARS+=",NUM_ENVS=${NUM_ENVS}"
EXPORT_VARS+=",AGENT_SCRIPT=${AGENT_SCRIPT}"
EXPORT_VARS+=",SETTLE_STEPS=${SETTLE_STEPS}"
EXPORT_VARS+=",STRATEGY_TARGET=${STRATEGY_TARGET}"
EXPORT_VARS+=",STRATEGY_MAX_ATTEMPTS=${STRATEGY_MAX_ATTEMPTS}"
EXPORT_VARS+=",STRATEGY_VERBOSE=${STRATEGY_VERBOSE}"
EXPORT_VARS+=",STRATEGY_MIN_SELECTED_PAIR_DISTANCE=${STRATEGY_MIN_SELECTED_PAIR_DISTANCE}"
EXPORT_VARS+=",STRATEGY_RAIL_EXTENT=${STRATEGY_RAIL_EXTENT}"

# Optional overrides — forward only when caller set them.
for v in \
  STRATEGY_IMAGES_PER_SCENE STRATEGY_REQUIRED_YES STRATEGY_REQUIRED_NO \
  STRATEGY_CAM_RED_THRESH STRATEGY_CAM_NO_RED_MAX \
  STRATEGY_AGENT_GOAL_THRESH STRATEGY_AGENT_CAMERA_THRESH \
  STRATEGY_AGENT_DEADZONE_DEG STRATEGY_AGENT_PERP_DEADZONE_DEG \
  STRATEGY_CAMERA_GOAL_DISTANCE STRATEGY_MAX_CAMERA_GOAL_DISTANCE \
  STRATEGY_MIN_CAMERA_GOAL_CLEARANCE STRATEGY_MIN_AGENT_CLEARANCE \
  STRATEGY_AGENT_OBSERVER_DISTANCE STRATEGY_AGENT_OBSERVER_JITTER \
  STRATEGY_MIN_OCCLUDER_CLEARANCE STRATEGY_OCCLUDER_INDEX \
  STRATEGY_DISTRACTOR_CLEARANCE \
  STRATEGY_OCCLUDER_SCALE_XY_MIN STRATEGY_OCCLUDER_SCALE_XY_MAX \
  STRATEGY_OCCLUDER_SCALE_Z_MIN STRATEGY_OCCLUDER_SCALE_Z_MAX \
  STRATEGY_DISTRACTOR_SCALE_MIN STRATEGY_DISTRACTOR_SCALE_MAX \
  STRATEGY_CANDIDATE_POINTS STRATEGY_AXIS_CANDIDATES \
  STRATEGY_MIN_VALID_CANDIDATES
do
  if [ -n "${!v:-}" ]; then
    EXPORT_VARS+=",${v}=${!v}"
  fi
done

cd "${JOB_DIR}"
sbatch --array=0-$((NUM_NODES - 1)) \
  --gres=gpu:${NUM_GPUS} \
  --time=${TIME_LIMIT} \
  --mem=${MEMORY} \
  --output=${LOG_DIR}/worker_%A_%a.out \
  --error=${LOG_DIR}/worker_%A_%a.err \
  --export="${EXPORT_VARS}" \
  generation_worker.sh
